version: '3'
services:
  webserver:
    build: ./webserver
    ports:
      - "9080:8080"
    networks:
      webnetwork:
        ipv4_address: 172.16.1.2
  reverse:
    build: ./proxy
    volumes:
      - ./proxy/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - "443:8080"
    networks:
      webnetwork:
        ipv4_address: 172.16.1.3
  modsecurity:
    build: ./modsecurity
    volumes:
      - ./modsecurity/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./modsecurity/crs-setup.conf:/etc/modsecurity/crs-setup.conf
      - ./modsecurity/modsecurity.conf:/etc/modsecurity/modsecurity.conf
      - ./modsecurity/mod_security2.so:/usr/local/apache2/modules/mod_security2.so
    ports:
      - "80:8081"
    networks:
      webnetwork:
        ipv4_address: 172.16.1.4
networks:
  webnetwork:
    ipam:
      config:
        - subnet: 172.16.1.0/24
          ip_range: 172.16.1.0/24
          gateway: 172.16.1.1
